name: npm audit

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - uses: oke-py/npm-audit-action@v1.7.3
        with:
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_labels: vulnerability,audit
          dedupe_issues: true
